set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_SYSROOT /opt/Xilinx/zcu104_rv_ss/sw/sysroot)
#set(CMAKE_STAGING_PREFIX /home/devel/stage)

set(tools /opt/Xilinx/SDK/2018.1/gnu/aarch64/lin/aarch64-linux)
set(CMAKE_C_COMPILER ${tools}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


set(ETHASHCL OFF)
set(ETHASHCUDA OFF)

set(COMPILE_STUBGEN OFF) 
set(HTTP_SERVER NO)
set(COMPILE_EXAMPLES NO) 
set(COMPILE_TESTS NO)



set( HAVE_FSETXATTR_5
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( HAVE_FSETXATTR_5__TRYRUN_OUTPUT
     "0"
     CACHE STRING "Output from TRY_RUN" FORCE)

set( HAVE_GLIBC_STRERROR_R
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT
     "0"
     CACHE STRING "Output from TRY_RUN" FORCE)

set( HAVE_POSIX_STRERROR_R
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( HAVE_POSIX_STRERROR_R__TRYRUN_OUTPUT
     "0"
     CACHE STRING "Output from TRY_RUN" FORCE)

set( HAVE_POLL_FINE_EXITCODE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

add_definitions(-DHAVE_POSIX_STRERROR_R=1)
set(HAVE_IN_ADDR_T YES)

